quarkus.devservices.enabled=false
# Conf 
quarkus.langchain4j.azure-openai."az-llama".chat-model.endpoint=${AZURE_OPENAI_ENDPOINT}
quarkus.langchain4j.azure-openai."az-llama".chat-model.api-key=${AZURE_OPENAI_API_KEY}
quarkus.langchain4j.azure-openai."az-llama".chat-model.deployment-name=${AZURE_OPENAI_DEPLOYMENT}
quarkus.langchain4j.azure-openai."az-llama".log-requests=true
quarkus.langchain4j.azure-openai."az-llama".log-responses=true
quarkus.langchain4j.azure-openai."az-llama".resource-name=chatgpt


#quarkus.langchain4j.openai.base-url=http://localhost:51838/v1
#quarkus.langchain4j.openai.api-key=sk-dummy
#quarkus.langchain4j.openai.chat-model.model-name=granite-3.2-8b-instruct-Q4_K_M.gguf
# Responses might be a bit slow, so we increase the timeout
#quarkus.langchain4j.openai.timeout=240s
#quarkus.langchain4j.openai.log-requests=true
#quarkus.langchain4j.openai.log-responses=true

# enable debug mode in quarkus
quarkus.log.level=INFO
# enable debug mode in langchain4j  

cron.expression=0 */1 * * * ?

## OLLAMA ##

#quarkus.langchain4j.ollama.debug=true
#quarkus.langchain4j.ollama.devservices.enabled=false
#quarkus.langchain4j.ollama.base-url=http://localhost:11434
#quarkus.langchain4j.ollama.chat-model.enabled=true
#quarkus.langchain4j.ollama.log-requests=true
#quarkus.langchain4j.ollama.log-responses=true

#quarkus.langchain4j.ollama.gemma.timeout=50s

quarkus.langchain4j.ollama.llama.chat-model.model-id=llama3.2:3b
quarkus.langchain4j.ollama.llama.timeout=50s
quarkus.langchain4j.ollama.llama.log-requests=true
quarkus.langchain4j.ollama.llama.log-responses=true
quarkus.langchain4j.ollama.llama.chat-model.temperature=0.5
quarkus.langchain4j.ollama.llama.chat-model.top-p=0
quarkus.langchain4j.ollama.llama.chat-model.top-k=0

#quarkus.langchain4j.ollama.gemma.chat-model.model-id=gemma3:1b
#quarkus.langchain4j.ollama.gemma.log-requests=true
#quarkus.langchain4j.ollama.gemma.log-responses=true
#quarkus.langchain4j.ollama.gemma.chat-model.temperature=0

#quarkus.langchain4j.ollama.nvidia.chat-model.model-id=nemotron-mini:4b
#quarkus.langchain4j.ollama.nvidia.log-requests=true
#quarkus.langchain4j.ollama.nvidia.log-responses=true
#quarkus.langchain4j.ollama.nvidia.timeout=50s
#quarkus.langchain4j.ollama.nvidia.chat-model.temperature=0
#quarkus.langchain4j.ollama.nvidia.chat-model.top-p=0
#quarkus.langchain4j.ollama.nvidia.chat-model.top-k=0

#quarkus.langchain4j.ollama.embedding-model.enabled=false
#quarkus.langchain4j.ollama.embedding-model.model-id=granite-embedding:278m

## MongoDB Configuration
#quarkus.mongodb.connection-string=mongodb://localhost:27017
#quarkus.mongodb.database=kala
#quarkus.mongodb.credentials.username=admin
#quarkus.mongodb.credentials.password=password
#quarkus.mongodb.devservices.enabled=false
#quarkus.mongodb.credentials.auth-mechanism=PLAIN


quarkus.naming.enable-jndi=true
quarkus.class-loading.removed-resources."io.quarkus\:quarkus-mongodb-client"=META-INF/services/com.mongodb.spi.dns.DnsClientProvider
quarkus.mongodb.connection-string=${MONGODB_CONNECTION_STRING}
#quarkus.mongodb.credentials.username=********
#quarkus.mongodb.credentials.password=********
quarkus.mongodb.devservices.enabled=false

fb.acces_token=${FB_ACCESS_TOKEN}